### ISSUE TITLE
chore: add `packageManager` option in `package.json`

### ISSUE THREAD

**Issue by nozomuikuta** [Boshen/javascript-parser-in-rust#14]
When I set up this project to fix #13, I found that configuration for corepack is not set up.
So, I tried to use the latest version of pnpm (because of `pnpm-lock.yaml`), and diffs are generated in the file.

I didn't include the diff in #13, but it's appreciated [`packageManager` option is defined in `package.json`](https://nodejs.org/api/corepack.html#configuring-a-package) for future developer experience.

**Comment by Boshen** [comment]
I added a packageManager

https://github.com/oxc-project/javascript-parser-in-rust/blob/3d7c2b9d509a3ef856340387f6e7385bd3ba2d1d/package.json#L55
