### ISSUE TITLE
[ask] I would like to create a pull request for a translation, but what would be the appropriate granularity for the PR?

### ISSUE THREAD

**Issue by ubugeeei** [Boshen/javascript-parser-in-rust#15]
Thank you for the wonderful project. 
Since discussions haven’t been opened, I am asking this question through an issue.

I know that part of this project has been translated into Japanese, and I would like to create PRs for translating the remaining parts. 
What granularity of PRs do you request us?

•	Everything all at once
•	Each page individually
•	Others

I would be grateful if you could tell me the method that would best suit your preferences.

**Comment by ubugeeei** [comment]
@Boshen 

Please help 🙏

**Comment by Boshen** [comment]
> What granularity of PRs do you request us?

Just dump content at your own pace and I'll blindly merge them, given I don't read Japanese ;-)

**Comment by ubugeeei** [comment]
Understood. I plan to submit a comprehensive pull request over the weekend 🙄
