### ISSUE TITLE
migrate to Rspress or VitePress ( ? )

### ISSUE THREAD

**Issue by ubugeeei** [Boshen/javascript-parser-in-rust#19]
ref: https://x.com/boshen_c/status/1723537621572612296?s=20

**Comment by Boshen** [comment]
I don't know if it's a good idea or not but I'm thinking of moving all the content to the main website under the learn section. Otherwise we'll wait a day for the vote.

**Comment by ubugeeei** [comment]
I think it's a great idea!

**Comment by nozomuikuta** [comment]
Whichever is chosen, I will help you migrate contents and rearchitecting contents in the main site. 🙋‍♂️

**Comment by Boshen** [comment]
> Whichever is chosen, I will help you migrate contents and rearchitecting contents in the main site. 🙋‍♂️

Thank you.

**Comment by ubugeeei** [comment]
It’s a very good resource, but it’s hard to imagine such a high-quality document being so hidden, so I’d like to find a way to make it more discoverable.🧐

**Comment by Boshen** [comment]
Tracking in https://github.com/oxc-project/oxc-project.github.io/issues/4

Discoverability could be an issue but maintaining two websites is another issue.
Discoverability should be relatively easier to solve than maintenance so let's go for a single website.
