### ISSUE TITLE
Some broken links that need to be fixed

### ISSUE THREAD

**Issue by mysteryven** [Boshen/javascript-parser-in-rust#22]
See https://github.com/oxc-project/javascript-parser-in-rust/actions/runs/6841174660/job/18601258603?pr=21

**Comment by suica** [comment]
Links under `https://rome.github.io` seem to be lost and the repo itself is not open-source (e.g. https://rome.github.io/tools/rome_js_parser/index.html), and links under `https://rome.tools` could still be viewed via web archive (e.g. https://web.archive.org/web/https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust).

**Comment by Boshen** [comment]
I may need to adjust the content if things aren't accessible anymore :-(

**Comment by mysteryven** [comment]
Fixed by #30
