### ISSUE TITLE
AST nodes contain String or &str?

### ISSUE THREAD

**Issue by Glyphack** [Boshen/javascript-parser-in-rust#32]
The guide uses String type in ast nodes(for example to hold variable name) But I see [in Oxc](https://github.com/web-infra-dev/oxc/blob/eff9cff048b6ab1c0b4ab9d4efc7098eb0b93a9e/crates/oxc_ast/src/ast/literal.rs#L250) they are &str instead. Is there any benefit to doing this in general or it's something specific to Oxc?

Wouldn't it require a clone when creating `AST` nodes from `TokenValue`?

For example in this snippet:
```
let variable_name = self.cur_token().value.clone();
let expr = Expression::Name(Box::new(Name {
    node: self.finish_node(node), // set the end of this node to previous token end offset
    id: variable_name,
}));
```

We need to use clone. Is there an alternative?

**Comment by Boshen** [comment]
The guide uses a `String` to avoid the intimidating lifetime annotation for new beginners.

For production use, we should strive to write a allocation-free parser 😉 

You can still move the token values if it's not used else where via `std::mem::take`.
