### ISSUE TITLE
Example code is not correct

### ISSUE THREAD

**Issue by magic-akari** [Boshen/javascript-parser-in-rust#4]
https://boshen.github.io/javascript-parser-in-rust/blog/grammar/#label-statement-is-legit

> The following syntax is correct, it returns a labelled statement (not object literal).

```JavaScript
const foo = (bar) => ({ baz: quaz });
```

In fact, it will return object literal.

**Comment by Boshen** [comment]
Nice catch, I probably wrote that too fast.
